theme = "github_dark_high_contrast"
# theme = "ayu_evolve"

[editor]
line-number = "relative"

[editor.file-picker]
hidden = false

[keys.insert.j]
k = "normal_mode" # Maps `jk` to exit insert mode
[keys.insert.J]
K = "normal_mode" # Maps `JK` to exit insert mode

[keys.normal."minus"]
h = ":lang helm"
y = ":lang yaml"

[keys.normal."space"]
F = "file_picker_in_current_buffer_directory"
