[language-server.helm]
command = "helm_ls"
args = ["serve"]

[language-server.golangci-lint]
command = "golangci-lint-langserver"
config = { command = ["/opt/homebrew/bin/golangci-lint", "run", "--enable-all", "--disable", "lll", "--out-format", "json", "--issues-exit-code=1"] }

[[language]]
name = "go"
language-servers = ["gopls", "golangci-lint"]
